modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="armors"
version="1.16.5-1.0.0"
displayName="Modern Armor"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png"
credits="Pillk"
#authors=""
#description='''. . .'''
[[dependencies.armors]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armors]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.5-4.1.0.0,)"

